branches:
  only:
    - develop

image: Previous Visual Studio 2015

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  nodejs_version: '6'
  #matrix:
  #  - nodejs_version: '6'
  #  - nodejs_version: '7'
  #  - nodejs_version: '8'
  #  - nodejs_version: '9'
  #  - nodejs_version: '10'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install
#matrix:
#  fast_finish: true
#  allow_failures:
#    - nodejs_version: 10
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run test
  #- node tools/test-watch.js
